### ISSUE TITLE
Change branch handling in docker deployment logic

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server#106]
~Maybe~ we should ~configure our `deploy-docker` step to~ handle branches with `/`'s in them properly, since those create an `invalid reference format` error with Docker.

We could do this by translating all `/`'s into `-`'s in the "tag" part of the image name.

But if we already have `-`'s, I'd like them to be separate. So maybe if that is the case, `/`'s get turned into `--`'s.

This would resolve the build failure on #105.

**Comment by hawkrives** [comment]
For safety, it'd have to do the single-double expansion first…

What about replacing `/` with `_` and doubling underscores, instead of hyphens? then most branches would look like `renovate_cool-dep-v1.6`?

otherwise, if we want `renovate--`, I'd prefer that we just change the renovate config prefix and do only do doubling if there's a `/`?

**Comment by hawkrives** [comment]
Resolved by https://github.com/frog-pond/ccc-server/pull/707

The docker-metadata step (https://github.com/docker/metadata-action) will, on push, transform `refs/heads/releases/v1` into `releases-v1`

(Now, I think we're still not deploying on branches, but this should fix the deployment issue.)
