### ISSUE TITLE
Institution-specific schemes

### ISSUE THREAD

**Issue by drewvolz** [frog-pond/ccc-server#9]
We need a separation between data for each institution. I'm part to blame for the lack of separation atm.

**Comment by hawkrives** [comment]
I'm going to call this "done", since we have subdomains (carleton.api.frogpond.tech, stolaf.api.frogpond.tech), separate code per server (institutions/$school), `npm run` scripts for each school (`npm run carls`, `npm run aao`), and a `docker-compose.yml` / nginx config with entries for each subdomain.
